services:
  - type: web
    name: drneal-aggarwal-site
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
